version: '3.6'
services:  #ricontrolla tutti le dipendenze dei container e cerca di aggiustarli bene con wait-for-it

##############################################################################
#BASE SERVICES
##############################################################################

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch  
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    networks:
      - elk
    restart: always

  kibana:
    image: kibana:7.16.2
    container_name: kibana      
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - elasticsearch  
    networks:
      - elk
    restart: always

  couchdb:
    image: couchdb
    container_name: nosql-database
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - 5984:5984
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: message-broker
    ports:
      - 5672:5672
      - 15672:15672 #admin web interface
    restart: always

  php:
    build: ./configs/php
    container_name: php
    ports:
      - 9000:9000
    volumes:
      #manca il voluma da mappare con tutte le cose statiche va mappato su /usr/share/nginx/html
      - ./source/index.php:/usr/share/nginx/html/index.php
      - ./configs/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always


# ##############################################################################
# #WEB SERVER - NGINX
# ##############################################################################

  web_server_1:
    image: nginx:1.13.8
    container_name: admin-web_server
    ports:
      - 8080:80
      - 443:443
    volumes:
    #manca il voluma da mappare con tutte le cose statiche va mappato su /usr/share/nginx/html
      - ./source/index.php:/usr/share/nginx/html/index.php
      - ./configs/nginx-admin/openssl:/cert
      - ./configs/nginx-admin/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - admin-server
    restart: always
      
  
  web_server_2: #questo funziona come na specie di load balancer vedi come esempio i config di quello del vitaletti
    image: nginx:1.13.8
    container_name: user-web_server
    ports: 
      - 8081:80
      #- 444:443 sempre se vogliamo che pure questo è ssl
    volumes:
      - ./configs/nginx-worker/default.conf:/etc/nginx/nginx.conf
    depends_on: 
      - worker_1
      - worker_2
      - worker_3
    restart: always
    


##############################################################################
#WORKER SERVERS -- ATTENZIONE ALLE DIPENDENZE IN package.json
##############################################################################

  worker_1:
    build: ./docker/worker 
    environment:
      - PORT=3001
      - SERVICE_NAME=node1
    depends_on:
      - couchdb
      - rabbitmq
      - superworker
      - admin-server
    command:  "./wait-for-it.sh -t 60 couchdb:5984 -- bash -c  './initialize.sh && node worker.js'"
    restart: always
     
  worker_2:
    build: ./docker/worker
    environment:
      - PORT=3002
      - SERVICE_NAME=node2
    depends_on:
      - couchdb
      - rabbitmq
      - superworker
      - admin-server
    command:  "./wait-for-it.sh -t 60 couchdb:5984 -- bash -c  './initialize.sh && node worker.js'"
    restart: always
  
  worker_3:
    build: ./docker/worker 
    environment:
      - PORT=3003
      - SERVICE_NAME=node3
    depends_on:
      - couchdb
      - rabbitmq
      - superworker
      - admin-server
    command:  "./wait-for-it.sh -t 60 couchdb:5984 -- bash -c  './initialize.sh && node worker.js'"
    restart: always

  superworker:
    build: ./docker/superworker
    depends_on:
      - couchdb
      - rabbitmq
      - admin-server
    command:  "./wait-for-it.sh -t 60 couchdb:5984 -- bash -c  './initialize.sh && node superworker.js'"
    restart: always

##############################################################################
#ADMIN SERVER
##############################################################################

  admin-server:
    build: ./docker/admin-server
    environment:
      - NODE_ENV=production
    ports:
      - 12345:3000
    depends_on:
      - couchdb
      - rabbitmq
      - php
      - kibana
    command:  "./wait-for-it.sh -t 60 couchdb:5984 -- bash -c  './initialize.sh && node admin-server.js'"
    restart: always

volumes:
  elastic_data: {}

networks:
  elk: